# Generated by Django 4.1.7 on 2023-05-10 10:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invite',
            old_name='from_user_id',
            new_name='from_user',
        ),
        migrations.RenameField(
            model_name='invite',
            old_name='to_user_id',
            new_name='to_user',
        ),
        migrations.AlterUniqueTogether(
            name='invite',
            unique_together={('from_user', 'to_user')},
        ),
    ]
